### ISSUE TITLE
Installation instructions seem to depend on Wagtail

### ISSUE THREAD

**Issue by spookylukey** [timonweb/django-dbbackup-ui#1]
In the instructions about urls.py, you have:

    url(r'^admin/', include(wagtailadmin_urls)),

Is this a mistake, or does the package depend on wagtail?

**Comment by timonweb** [comment]
Nice catch! No it doesn't. It support Django admin by default and if you need Wagtail support you just enable additional sub module. Fixed read me, thanks for your report!
